# Generated by Django 4.1.1 on 2022-10-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menapp', '0004_delete_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
