# Generated by Django 4.1.1 on 2022-10-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menapp', '0005_alter_login_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronometro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclos', models.CharField(max_length=10)),
                ('estudio', models.CharField(max_length=10)),
                ('descanso', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
