# Generated by Django 4.1.1 on 2022-11-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menapp', '0008_resumen_delete_cronometro'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen',
            name='titulo',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
