# Generated by Django 4.1.1 on 2022-11-10 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menapp', '0009_resumen_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumen',
            old_name='titulo',
            new_name='title',
        ),
    ]
