# Generated by Django 4.1.1 on 2022-11-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menapp', '0013_resumen_usuario_alter_resumen_resumen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumen',
            name='usuario',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
