# Generated by Django 4.1.1 on 2022-11-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menapp', '0014_alter_resumen_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenaza', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('usuario', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
