# Generated by Django 4.1.1 on 2022-11-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menapp', '0015_amenaza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenaza',
            name='amenaza',
            field=models.CharField(max_length=50),
        ),
    ]
