# Generated by Django 4.1.1 on 2022-11-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menapp', '0017_alter_amenaza_amenaza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumen',
            name='resumen',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='titulo',
            field=models.CharField(max_length=40),
        ),
    ]
