# Generated by Django 4.1.1 on 2022-10-25 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menapp', '0003_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
